apiVersion: apps/v1
kind: Deployment
metadata:
  name: workspace-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workspaceservice
  template:
    metadata:
      labels:
        app: workspaceservice
    spec:
      containers:
        - name: workspaceservice
          image: mzdevi/workspaceservice:latest
          env:
            - name: CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: workspace-credentials
                  key: CONNECTION_STRING
            - name: RABBITMQ_HOST
              valueFrom:
                secretKeyRef:
                  name: workspace-credentials
                  key: RABBITMQ_HOST
            - name: RABBITMQ_PORT
              valueFrom:
                secretKeyRef:
                  name: workspace-credentials
                  key: RABBITMQ_PORT
---
apiVersion: v1
kind: Service
metadata:
  name: workspace-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: workspaceservice
  ports:
  - name: workspaceservice
    protocol: TCP
    port: 80
    targetPort: 80
