apiVersion: v1
kind: Service
metadata:
  name: workspaceservice-srv
spec:
  type: NodePort
  selector:
    app: workspaceservice
  ports:
  - name: workspaceservice
    protocol: TCP
    port: 8080
    targetPort: 8080
